### ISSUE TITLE
(SOLVED)"No devices found...", red square on extension icon

### ISSUE THREAD

**Issue by meltdown03** [pdf/kdeconnect-chrome-extension#1]
Version 0.0.4
OS: Antergos 17.1
DE/WM: Gnome
AUR/kdeconnect-git r1584.29986ac-1 (synced 2/1/2017)
Chrome-untable (tried on Stable Chrome and Chromium as well)

Installed Chrome extension and script. All went ok but seem to have no connection between the extension and kdeconnect. Are there ports to open in firewall?
All other functions of kdeconnect do work.

EDIT:
I disabled UFW and still no devices found. I am running Gnome as my Windows Manager/ Desktop Environment also.

**Comment by pdf** [comment]
Hey, sorry for the delay getting back to you - I missed the notification for this issue somehow.

The red badge means the extension is having trouble communicating with the host application, I should probably add a status message in the popup to that effect.  There are no ports to open - chrome talks to the native host directly (via stdin/stdout).

If you start chrome/chromium from a terminal (`google-chrome` or `chromium`), do you see a message like the following?

```
Can't find manifest for native messaging host com.0xc0dedbad.kdeconnect_chrome
```

If so, you may need to try installing the native host again (see the README).

I have a feeling I know why it didn't install correctly for you - you need to select the browsers to install for from the menu in the installer using the `Space` key, and then hit `Enter`.  I've made this clear in the README, and added these instructions to the prompt in the installer to avoid future confusion.  The installer also now requires the user to make a valid browser selection, or it will refuse to continue.  Apologies for not making this clearer.

Please try installing the latest version, and let me know if everything is sorted out for you.

**Comment by meltdown03** [comment]
I had it all installed and set up correctly and still nothing...Until today,with the Version 0.0.5 update and a new build of kdeconnect from AUR, all is working great. Thank you,
