### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Mte90** [pdf/kdeconnect-chrome-extension#10]
Also Firefox support the Native messaging API and the rest of api of webextensions so I think that a port will be easy :-)

**Comment by pdf** [comment]
I've taken a look, and there are some incompatibilities.  Some are easy enough (if annoying) to work around, but the major one is that Firefox's async extension API calls use promises, where as Chrome's use callbacks.  This means refactoring most of the plugin code and adding a polyfill for Chrome make it work on both.

I will take a look at sorting this out, no promises (_puns!_) on timeline though.

**Comment by pdf** [comment]
Submitted and awaiting approval: https://addons.mozilla.org/en-US/firefox/addon/kde_connect/

You will want the [latest release](https://github.com/pdf/kdeconnect-chrome-extension/releases/latest) of the native host for Firefox installation support.

**Comment by pdf** [comment]
Took a while to get a reviewer due to the use of native host, but it should be live now if you'd like to try it out.

**Comment by Mte90** [comment]
Installed :-D
