### ISSUE TITLE
Firefox not working

### ISSUE THREAD

**Issue by juanluisbaptiste** [pdf/kdeconnect-chrome-extension#17]
Hi, 

When installing the host program to be used with firefox I get this error:
```
$ ./kdeconnect-chrome-extension -install 
Select browser(s) for native host installation (Space to select, Enter to confirm):
  ◯  Chrome/Opera
  ◯  Chromium
  ◯  Vivaldi
> ◉  Firefox
  ◯  Custom
invalid argument
<nil>
panic: invalid argument
        panic: nil

goroutine 1 [running]:
main.doInstall.func1(0xc4200fa010, 0xc420053b60)
        /storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/install.go:67 +0xc7
panic(0x6163e0, 0xc420044140)
        /usr/lib/go/src/runtime/panic.go:491 +0x283
main.doInstall.func2(0x0, 0xc420053b60)
        /storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/install.go:77 +0xc7
main.doInstall(0xc420104060, 0x2d, 0x65ad06, 0x7, 0x664436, 0x20, 0x784e40, 0xc4200f83c0)
        /storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/install.go:81 +0x6c8
main.install(0x0, 0x0, 0xc42007d140)
        /storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/install.go:242 +0x1799
main.main()
        /storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/main.go:122 +0xad
```
Any ideas ?

**Comment by pdf** [comment]
Is this an upgrade, and is Firefox already running? If so, make sure you close Firefox first, as the upgrade instructions in the README suggest.  If this is the case, let me know and I'll just try to improve the error message.

**Comment by juanluisbaptiste** [comment]
No, first time install, no firefox running.

**Comment by pdf** [comment]
I've updated the v0.1.3 host binary with fixes to the error handling, please grab it again from here:

https://github.com/pdf/kdeconnect-chrome-extension/releases/download/v0.1.3/kdeconnect-chrome-extension-v0.1.3-linux_amd64.tar.xz

Try it and let me know what output you get now.

**Comment by juanluisbaptiste** [comment]
Now I get this:

close /home/juancho/Downloads/kdeconnect-chrome-extension: file already closed
panic: close /home/juancho/Downloads/kdeconnect-chrome-extension: file already closed

**Comment by pdf** [comment]
Apologies, I copy-pasta'd a line when making the last logging improvements, please download and try one more time. Thanks.

**Comment by pdf** [comment]
Did you have any luck @juanluisbaptiste ?

**Comment by juanluisbaptiste** [comment]
Sorry I forgot to update, yes, it works now, thanks.

**Comment by pdf** [comment]
Great! I wish I was certain of why it wasn't working for you in the first place, but as a bonus we have better error handling now, so if it ever happens again, we should get useful logs.  Thanks for the response.
