### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by hhl** [pdf/kdeconnect-chrome-extension#18]
Hi,
i have installed the APP via https://addons.mozilla.org/en-US/firefox/addon/kde_connect/
kdeconnect is running without any issue!

but the phone is not recognized by the browser APP.
Only thing I see is a red square and "No devices found ..."
and after a while
Error could not connect to native host
Error version response .... (or similar)

System: debian sid/unstable
KDE Connect Add On 0.1.4
```
$ LANG=C apt policy firefox kdeconnect
firefox:
  Installed: 57.0.4-1
  Candidate: 57.0.4-1
  Version table:
     58.0~b14-1 1
          1 http://ftp.debian.de/debian experimental/main amd64 Packages
 *** 57.0.4-1 500
        500 http://ftp.debian.de/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
kdeconnect:
  Installed: 1.0.3-1
  Candidate: 1.0.3-1
  Version table:
 *** 1.0.3-1 500
        500 http://ftp.debian.de/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

Edit:
same behaviour with chrome
```
google-chrome-stable:
  Installed: 63.0.3239.132-1
  Candidate: 63.0.3239.132-1
  Version table:
 *** 63.0.3239.132-1 500
        500 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status```

**Comment by pdf** [comment]
Did you follow the instructions in the README of this repository to install the native host?

**Comment by hhl** [comment]
oh, i am sorry, i stumbled over your add on installed it, but didn't took a look to the github side.
Now it is working, i am sorry. Maybe give a short description at the addon side, or let a popup-warning appear if no device/host found, aka: did you download and installed the native host like described at .....
or maybe find a way to do it automagicly with asking to allow ......

greetings and sorry for the noise

**Comment by pdf** [comment]
The addons page does mention this:

> This extension relies on a Native Messaging Host to communicate with KDE Connect devices. See https://github.com/pdf/kdeconnect-chrome-extension for installation.

But I'll see if there's a way I can make it more obvious from inside the addon (making the addon cross-browser unfortunately makes it hard to detect the missing native host reliably).

Glad you're up and running in any case :+1:
