### ISSUE TITLE
No devices found... message on Firefox / KDE Neon 

### ISSUE THREAD

**Issue by SMietzner** [pdf/kdeconnect-chrome-extension#19]
Hi!
I installed the Firefox Extension on my KDE Neon machine. KDE Neon comes with KDE-Connect and it connects flawlessly with my Smartphone. But the Firefox Extension doesn't? Do I have to install something else?
KDE Neon / xenial
kdeconnect  1.2
Firefox 58beta

Help would be appreciated!

**Comment by pdf** [comment]
See the README at https://github.com/pdf/kdeconnect-chrome-extension

**Comment by SMietzner** [comment]
Thanks for the fast response. Works now. Exactly what I was looking for! 
I read the instructions, but I thought 'native host' referred to KDE Connect which was already installed on my machine. My bad.
Happy now! Thanks for help and this awesome AddOn!

**Comment by pdf** [comment]
Glad you're up and running :+1:
