### ISSUE TITLE
Download link for release v0.0.5 isn't working

### ISSUE THREAD

**Issue by jelinekp** [pdf/kdeconnect-chrome-extension#2]
https://github.com/pdf/kdeconnect-chrome-extension/releases/tag/v0.0.5
I have tried it on many devices with the same result: github-cloud.s3.amazonaws.com took too long to respond...

**Comment by pdf** [comment]
I think github was having problems - I didn't get a notification for this issue either.

I'm going to close this as I don't believe this is still an issue.  If you are still having problems, please feel free to re-open.
