### ISSUE TITLE
aur package?

### ISSUE THREAD

**Issue by overclockedllama** [pdf/kdeconnect-chrome-extension#20]
i would really appreciate if you could package your amazing software with the AUR as it would make installation and keeping up to date tons easier for many users. AUR packaging is pretty simple by the way :) If you need any help feel free to ask

**Comment by pdf** [comment]
I'm afraid I have very little experience with AUR packaging.

I should also mention that the official Plasma browser extension will be ready for general release in the near future, and I'd expect that to arrive in official repos.

**Comment by overclockedllama** [comment]
What do you mean by the official Plasma browser extension?

**Comment by pdf** [comment]
https://github.com/KDE/plasma-browser-integration
https://www.youtube.com/watch?v=WGhrR1HsCOM

**Comment by overclockedllama** [comment]
noice
