### ISSUE TITLE
Android app does not send files to PC

### ISSUE THREAD

**Issue by gregharvey** [pdf/kdeconnect-chrome-extension#23]
Hi,

I just started using KDE Connect for Fedora Linux and your Android app. Almost everything works fine _except_ I cannot send files _from_ the Android phone _to_ the PC. It works the other way, the PC can send to the Android phone. I suspected firewall issues so I set firewalld in Fedora to log all denied traffic and tailed journalctl while trying to send files to the PC, but that yielded nothing. There was literally zero lines logged in journalctl. There's no error message, I click Share on the phone, get the list of connected devices, click my PC and it closes, as though Android thinks it's gone - but it never arrives. The weirdest thing is no logging at all on the Linux side, as though it doesn't even try.

The phone is a Blackview P2 running the official upgrade to Android 7.0 from the Blackview forums. I don't expect you to try and debug a specific handset of course, just wondering if you've had similar reports from other Android 7.0 users or if there are some logs on the phone I can give you to help figure out what's going on? :-)

Thanks!

Greg

**Comment by pdf** [comment]
This is the project for a browser extension, not the main KDE Connect project - you should report this elsewhere.

**Comment by gregharvey** [comment]
Oops, my bad! Not sure how I didn't realise. For anyone else surfing in, the **right** place to raise a bug is https://bugs.kde.org
