### ISSUE TITLE
I don't have playback controls on chrome or firefox?

### ISSUE THREAD

**Issue by JarradRTait** [pdf/kdeconnect-chrome-extension#28]

**Comment by JarradRTait** [comment]
To resolve in ubuntu 18.04

sudo add-apt-repository ppa:kubuntu-ppa/backports
sudo apt install plasma-browser-integration
install the Plasma Integration extension

**Comment by pdf** [comment]
This is also the wrong project - plasma-browser-integration is the official browser plugin and has its own repository.
