### ISSUE TITLE
No devices found (with native messaging host installed)

### ISSUE THREAD

**Issue by therealfarfetchd** [pdf/kdeconnect-chrome-extension#29]
Same as #18 and #19... except I do have the native messaging host installed. Without it it shows a red icon on the extension and some errors, and with it it just says "No devices found..." The native messaging host is running:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/3987560/61173450-d2632800-a593-11e9-82c6-a69af33edc8a.png">

<img width="124" alt="image" src="https://user-images.githubusercontent.com/3987560/61173457-e018ad80-a593-11e9-87b9-1e5ff3b32ecc.png">

And there are in fact available/online devices in KDE Connect:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/3987560/61173467-00486c80-a594-11e9-8cf7-ac1338216917.png">

**Comment by pdf** [comment]
Hmm, what version of kde-connect are you using?

**Comment by therealfarfetchd** [comment]
kdeconnect-1.3.4 (this is on Gentoo, by the way)

**Comment by pdf** [comment]
Does `kdeconnect-cli` work, and is Gentoo (or your desktop profile, or use flags) doing anything unusual with dbus? What does `echo $DBUS_SESSION_BUS_ADDRESS` output?

**Comment by therealfarfetchd** [comment]
`kdeconnect-cli -l` works correctly:

    % kdeconnect-cli -l
    - Motorola: 4334beb68590bcf4 (paired)
    - marco@yoop: _1eb131a9_9d6b_414e_9869_f3824e280931_ (paired)
    2 devices found

`DBUS_SESSION_BUS_ADDRESS='unix:abstract=/tmp/dbus-3Gcpd1KJYM,guid=c0f728e65921e5feffcb1cd55d2b0dee'`

I did copy this firefox profile from a different OS install (arch) on the same PC, where my username was different, could that have something to do with it? Although I think firefox profiles are supposed to be portable. (It worked fine on the arch install, and also currently works correctly on the other arch machine I have)

**Comment by pdf** [comment]
That might be related, though I'm not sure exactly how. You could try running in a clean Firefox profile, and reinstalling the native client (use the Upgrading instructions in the README).

**Comment by therealfarfetchd** [comment]
That was actually it, created a new firefox profile and installed the extension, and it worked without having to do anything else. Now, how would I get this to work on the old profile...

**Comment by therealfarfetchd** [comment]
It's suddenly working now... did you change anything? The only thing I changed is to update firefox to 68.0.1 and remove USE="lto" because the new firefox failed to compile with it.

**Comment by pdf** [comment]
No changes on this end, perhaps there was a Firefox bug? Closing this, feel free to reopen if you have further issues.

**Comment by juanluisbaptiste** [comment]
Hi,

I'm having the same issue with the latest version. kdeconnect-cli can see fine my devices:

kdeconnect-cli -l
- HUAWEI: 2fe7db6e67950d7a (paired)
- Sony: 9bc639d2f247b925 (paired)

But firefox says it cannot find any devices. 

I did close my browser, run the command ./kdeconnect-chrome-extension -install, selected firefox before reopening my browser.

**Comment by pdf** [comment]
@juanluisbaptiste what version of Firefox are you using?
Can you open `about:debugging`, go to `This Firefox`, find the extension and click `Inspect`, reload with <Ctrl-R>, then paste the console log?

**Comment by juanluisbaptiste** [comment]
Hi,

Firefox version: 70.0.1

Which page should I reload with ctrl R ? the inspect page ? if yes that command does not work to reload it.

**Comment by juanluisbaptiste** [comment]
Sorry, depending on which tab you are it reloads or not. On console tab I see this:

TypeError: can't access dead object
webconsole.js:298:9
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://41a85547-ad50-4975-96c8-892580e91c1b/js/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map

TypeError: can't access dead object

**Comment by pdf** [comment]
Is that all? Those errors look like they're just from the debugger itself, there don't appear to be any errors thrown by the extension.

If you have the latest binary from the releases page here, can you run `kdeconnect-browser-extension -devices` from a terminal?
