### ISSUE TITLE
Support for brave browser

### ISSUE THREAD

**Issue by gmparker2000** [pdf/kdeconnect-chrome-extension#30]
I would love to have this working in brave browser (https://brave.com/).  The extension installs but cannot find any devices.

**Comment by pdf** [comment]
Works fine on Brave here, please provide the following:

 - OS/distro/version: [e.g. Ubuntu 18.04]
 - Browser/version [e.g. chrome 76, firefox 68]
 - kdeconnect-cli version [`kdeconnect-cli --version`]
 - kdeconnect-cli devices [`kdeconnect-cli --list-devices`]
 - kdeconnect-chrome-extension version [`kdeconnect-chrome-extension -version`]

**Comment by gmparker2000** [comment]
That's great that it should work.  When I ran the install I picked chromium.  Details are:

**OS**
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"

**Browser**
Brave
Version 0.67.119 Chromium: 76.0.3809.72 (Official Build) unknown (64-bit)

**kdeconnect-cli**
kdeconnect-cli 1.3.5

**kdeconnect-cli devices**
- Greg's phone: fc2ec7f768aac975 (paired and reachable)
1 device found

**kdeconnect-chrome-extension version**
kdeconnect-chrome-extension version 0.1.3, built with go1.9.2

**Comment by pdf** [comment]
Please download [this pre-release](https://github.com/pdf/kdeconnect-chrome-extension/releases/download/v0.1.5/kdeconnect-chrome-extension-v0.1.5-linux_amd64.tar.xz), extract it and run `./kdeconnect-chrome-extension -devices`

**Comment by gmparker2000** [comment]
Not working in the browser.  I get this:

 kdeconnect-cli --list-devices
- My phone: fc2ec7f768aac675 (paired and reachable)
1 device found

**Comment by pdf** [comment]
@gmparker2000 can you please post the output from the native host from my last message (I made a test build of the native host with a flag to output the devices it sees)?

**Comment by gmparker2000** [comment]
I grabbed the pre-release.  I ran it and got:

 ./kdeconnect-chrome-extension --devices
- Greg's phone: fc2ec7f768aac975 (paired: true; reachable: true)

Is this what you want?

**Comment by pdf** [comment]
Great thanks, so it looks like the native host can talk to DBUS/kdeconnect okay, but somehow the browser extension is not getting that information. The extension _should_ display an error in that case, so I'm a little confused.

Can you right-click the extension icon, select `Manage Extensions`, enable `Developer Mode` top-left, then enable `Collect Errors`. Restart your browser, click the extension icon once, then right-click it and select `Manage Extensions` again.  If there are any errors, there will be an extra section there where you can view them, please post them here if they exist.

Sorry for the long-winded troubleshooting, but I can't reproduce any problems here.

**Comment by gmparker2000** [comment]
No error on the extension page.  If I turn on developer tools and inspect the background page I see a bunch of errors on the console:

background.js:54 Missing message parameters {type: "typeVersion"}
postMessage @ background.js:54
onMessage @ background.js:70
(anonymous) @ browser-polyfill.min.js:1

and 

Error in event handler: TypeError: Cannot read property 'postMessage' of null
    at postMessage (<URL>)
    at onMessage (<URL>)
    at <URL>


Happenning here:

function postMessage(msg) {
    if (!port || !msg || !msg.type) {
        console.error('Missing message parameters', msg);
    }
    port.postMessage(msg);
}

**Comment by pdf** [comment]
Seems to be having trouble talking to the native host in an unusual way. I'll try and make some time tonight to do some testing, but nothing obvious jumps out.

**Comment by zany130** [comment]
same issue here

**Comment by pdf** [comment]
I'm struggling to reproduce, which makes this tough for me to diagnose. I'll have to try spinning up a VM to test in a clean environment, but I just haven't had the time recently.

**Comment by hauweg** [comment]
Yes, support for Brave please <3

**Comment by pdf** [comment]
Thing is, it works fine on Brave here, so it's confusing why it doesn't work for some other people with that browser.

**Comment by malachy47** [comment]
I came across this thread via search as I too am having the same issue. KDE Connect works fine from the tray, but the Brave extension does not see any device. Running KDE Neon (Ubuntu 20 based).

**Comment by pdf** [comment]
Seems Brave messed something up in some versions wrt paths for native messaging hosts. Try choosing Chrome from the native host installer and see if that works.

https://github.com/brave/brave-browser/issues/5074

**Comment by MatheusR42** [comment]
Here I get no device found.

Kubuntu 20
kdeconnect-cli 1.4.0
Brave V1.21.74

**Comment by manavdesai27** [comment]
@pdf I am facing the same issue. On running
 ./kdeconnect-chrome-extension -devices
I get the following:

Redmi K20 Pro: efa2d98185289bc2 (paired: true; reachable: false)

Can you help me fix this. I need to be able to run this extension on brave.

**Comment by pdf** [comment]
Try with the v0.1.6 release just published, and choose `Brave` when installing, hopefully this works for Brave users on current versions - they've made quite a mess of the paths.
