### ISSUE TITLE
This add-on is not available on your platform on Firefox 70

### ISSUE THREAD

**Issue by gerroon** [pdf/kdeconnect-chrome-extension#31]
Hi

Does this extension work on 70? Becasue when I open the Firefox addon page it says the text in the title and does not let me install it.

thanks

**Comment by pdf** [comment]
The add-on works on Firefox 70, but is Linux-only (#4).

**Comment by gerroon** [comment]
I am on Linux too

**Comment by pdf** [comment]
Are you on normal Firefox or a fork? Do you have any add-ons that might present an alternative User-Agent?

**Comment by pdf** [comment]
Tested with a clean profile and all appears to work here:
![Firefox70-Screenshot_20191103_094154](https://user-images.githubusercontent.com/146192/68077808-65afba00-fe1e-11e9-9409-9ebaf4faec78.png)

**Comment by gerroon** [comment]
Good question. I use user.js but I do not know how to reset that version thing. I will take a look at it.
