### ISSUE TITLE
Not working with gsconnect in Firefox.

### ISSUE THREAD

**Issue by rolandixor** [pdf/kdeconnect-chrome-extension#32]
**Describe the bug**
Doesn't work with Gsconnect.

**To Reproduce**
1. Install it in Firefox under Gnome
2. Click on the toolbar button.
3. No devices found.

**Expected behavior**
It should show available devices.

**Screenshots**

**Desktop (please complete the following information):**
 - OS/distro/version: Ubuntu 19.10
 - Browser/version: Firefox 70
 - I'm using Gsconnect.
 - kdeconnect-chrome-extension version: 0.1.4.

**Comment by pdf** [comment]
I suspect GSConnect has an entirely different API, and they appear to have their own browser extensions. As such, there are currently no plans to implement support for GSConnect in this extension.
