### ISSUE TITLE
`GLIBC_2.32' not found

### ISSUE THREAD

**Issue by erayerdin** [pdf/kdeconnect-chrome-extension#41]
**Describe the bug**
```
./kdeconnect-chrome-extension: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./kdeconnect-chrome-extension)
```

**To Reproduce**
1. Download latest version and extract it.
2. `sudo ./kdeconnect-chrome-extension -install`
3. "./kdeconnect-chrome-extension: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./kdeconnect-chrome-extension)"

**Expected behavior**
Install it.

**Desktop (please complete the following information):**
 - OS/distro/version: Ubuntu 20.04.2 LTS
 - Browser/version Version 91.0.4472.114 (Official Build) (64-bit) | Installed from official source.

**Comment by pdf** [comment]
Thanks for reporting - please download the latest version again, and retry. I've rebuilt it without CGO, which should resolve your issue. If the problem persists somehow, please re-open.

**Comment by erayerdin** [comment]
FYI: Oddly, I've successfully installed this on another new machine.

**Comment by pdf** [comment]
I rebuilt the latest binary to remove the possibility of that error occuring, so if you downloaded it again, it is expected that this is resolved. Previously, you would receive that error depending on which version of GLIBC you had installed, now we don't link against GLIBC at all.
