### ISSUE TITLE
Errors in Brave

### ISSUE THREAD

**Issue by irthomasthomas** [pdf/kdeconnect-chrome-extension#46]
"No Device Found" in Brave browser but Firefox is connected OK.
Devuan (Debian stable sans systemd)
Brave 1.38.119
kdeconnect-cli 20.12.3
kdeconnect-cli --list-devices
- CPH2305: 9dc4dc2730bd9920 (paired and reachable)

Error log:
- Uncaught (in promise) Error: No tab with id: 51.
- Missing message parameters [object Object]
- Cannot read properties of null (reading 'postMessage')
- Disconnected from native host: Specified native messaging host not found.

Cheers - Tommy

**Comment by pdf** [comment]
Is Brave installed from apt? Brave seems to have a real problem deciding where to store their native messaging hosts consistently (see #30).

You can try running the installer again for all of Chrome, Chromium and Brave, just in case they've gone back to one of the old paths, or if you can work out what the currently correct native messaging host path is meant to be for that browser on your distro, let me know and I'll try to get the installer updated (or you can choose a custom browser from the installer and flil in the right path).

**Comment by ryanfantus** [comment]
I have the same issue on Arch with Brave installed via the [brave-bin](https://aur.archlinux.org/packages/brave-bin) package in the AUR.

I installed the plugin via the chrome.google.com frontend, should I attempt installing a different way?

**Comment by pdf** [comment]
@ryanfantus did you install the native messaging host from this repository? If so, which options did you select during install?

**Comment by ryanfantus** [comment]
Guess I should RTFM :P. Oops.
