### ISSUE TITLE
[Firefox - Windows 10]Could not connect to native host

### ISSUE THREAD

**Issue by Milor123** [pdf/kdeconnect-chrome-extension#49]
Hi guys, I am trying using this addon on my firefox stable lasted version (Note: I;'ve tried it in chrome too) but show this error:

![image](https://user-images.githubusercontent.com/14153649/177614639-c58aba13-787b-4def-adb7-5c3b41840e0f.png)

My phone Android 12L is paring with my Windows 10 (I've tried to delete client from windows and install from Microsoft store, and re-paring with my phone) 

But same shows the error, it occurs in both in firefox and chrome.
What should I do?

Devices details:
Windows 10 21H2
Android 12.1 (KDE 1.19.1 > Fdroid Package)
Firefox stable and chrome stable
Thank u very much guys !!!!

**Comment by pdf** [comment]
This extension relies on a native host executable to function, and I've not yet completed integrating Windows support (#39 #4). I will find the time one day, but not today.

**Comment by Milor123** [comment]
> This extension relies on a native host executable to function, and I've not yet completed integrating Windows support (#39 #4). I will find the time one day, but not today.


Ohh understand, thank you very much bro!!!
