### ISSUE TITLE
Add a button to clear the device history list

### ISSUE THREAD

**Issue by oldherl** [pdf/kdeconnect-chrome-extension#52]
**Is your feature request related to a problem? Please describe.**
I have been using kdeconnect for a long time and now my device list in the popup menu is very long.
Many of them are devices that I no longer use or have been flashed a new OS and got duplicated.
This brings difficulty to find the one I want.

**Describe the solution you'd like**
Add a button somewhere to clear this list.

**Describe alternatives you've considered**
Or better, delete the specified unneeded ones.

**Additional context**
![image](https://user-images.githubusercontent.com/172495/227750612-559f0992-4551-494e-8012-3832ebc13897.png)

**Comment by pdf** [comment]
I'm not super-interested in duplicating functionality that exists in the regular kdeconnect application - delete the devices from there and they won't show up in the browser extension any more.

**Comment by oldherl** [comment]
Thanks! Didn't realize they share the same list.
