### ISSUE TITLE
panic: read unix , error while install on debian unstable

### ISSUE THREAD

**Issue by hhl** [pdf/kdeconnect-chrome-extension#55]
**Describe the bug**
When I try to install the extension for FF I get the following error;

```
# ./kdeconnect-chrome-extension -install
panic: read unix @->/run/user/1000/bus: recvmsg: connection reset by peer

goroutine 1 [running]:
main.init.0()
        /storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/main.go:122 +0x247
```
**Desktop (please complete the following information):**
 Debian unstable, full-upgraded
Desktop: KDE Plasma

```
System:
    Kernel: 6.4.7-1-siduction-amd64 arch: x86_64
    bits: 64 compiler: gcc v: 13.1.0 Desktop: KDE Plasma v: 5.27.5 tk: Qt
    v: 5.15.10 wm: kwin_wayland dm: SDDM Distro: siduction 22.1.2
    base: Debian GNU/Linux trixie/sid
```

 - Browser/version: Mozilla Firefox 115.0.2
 - kdeconnect-cli version 22.12.3
 - kdeconnect-cli devices: - poco: 97b57d25ef287d37 (paired and reachable)
1 device found

 - kdeconnect-chrome-extension version: kdeconnect-chrome-extension-v0.1.6-linux_amd64

**Smartphone (please complete the following information):**
 - Device: poco x3
 - OS: android 12
 - Browser  FF
 - Version 115.2.1

**Comment by pdf** [comment]
Are you using apparmor or SELinux or something that might restrict access to the user DBUS session? Or an alternative DBUS implementation?

Check security logs for denials to that socket.

**Comment by hhl** [comment]
Well, finally I managed to install it, the package _**dbus-x11**_, which includes the _**“dbus-launch”**_ command, was missing.

Maybe it will be a good idea to mention to check if that piece of software is installed (debian unstable/sid), and if not, _apt install dbus-x11_.

**Comment by pdf** [comment]
Hmm, looking at the description for that deb package I suspect that **dbus-user-session** would also do the job, but _some_ package that provides a session bus is required, and I'd be surprised if a bunch of other stuff wasn't non-functional without this facility available. Kinda surprised that some meta-package or other wouldn't install one of these as a dep.

I'll close this out for now as I've never heard of anyone else hitting this, but if it shows up again we'll know what to look for, and I may add explicit docs.

**Comment by hhl** [comment]
Strange, **_dbus-user-session_** was/is installed, and I got the explicit message to install **_dbus-X11_** if I wanted to use the _**dbus-launch**_ command!
