### ISSUE TITLE
Add option to hide context menu entry and only show icon in the top bar

### ISSUE THREAD

**Issue by ByteHamster** [pdf/kdeconnect-chrome-extension#6]

**Comment by pdf** [comment]
Should be available once publishing to the store is complete.

**Comment by ByteHamster** [comment]
It's impossible for me to _click_ on the checkbox because it is covered below the **controls** container. See attached image.

![screenshot_20170620_080150](https://user-images.githubusercontent.com/5811634/27318885-e4c55c4a-558e-11e7-8bf4-765464bdea38.png)

**Comment by pdf** [comment]
What resolution display are you using, out of curiosity?

It seems that Chrome is setting the size (max-height) of the options dialog wrapper by some metric I don't understand.  My options dialog is never that small, even if the window is resized to be smaller than the dialog.

![kdeconnect_screenshot_20170620_161507](https://user-images.githubusercontent.com/146192/27319234-c0d0203c-55d3-11e7-8eb8-65e995e2c333.png)

I will change the CSS and try to hack the rendering to match your output, to ensure this works as expected.

**Comment by ByteHamster** [comment]
Thanks, it's fixed now

I am using Chromium on my PC and laptop with 1680x1050 and 1600x900. Both devices had the problem.
