### ISSUE TITLE
Broken device icon

### ISSUE THREAD

**Issue by ByteHamster** [pdf/kdeconnect-chrome-extension#8]
The extension is trying to show the icon `images/smartphone-trusted.svg`, which leads to a broken image.

**Comment by pdf** [comment]
That's a weird state, I'll add icons for it, but I've never seen the state returned as anything other than `connected` or `disconnected`.  Can you still send when it's in this state?

**Comment by ByteHamster** [comment]
Yes, I can send without any problems. Not sure how to reproduce this, but I have seen the broken icon this morning too.

**Comment by pdf** [comment]
Okay, if you can still send we don't need any other changes, I'll just add the icon.

**Comment by ByteHamster** [comment]
Thanks a lot! Sorry for creating so much work for you today

**Comment by pdf** [comment]
No problem! Hopefully we have everything sorted now :thumbsup:
